[workspace]

members = [
    "get_image_lambda",
    "get_or_set_reaction_lambda",
    "set_favorite_recent_lambda",
    "daily_setup_lambda",
    "lambda_utils"
]

[workspace.dependencies]
sst_sdk = "0.1.0"
